# Generated by Django 3.0.2 on 2020-05-18 12:43

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0002_image_date_created'),
        ('accounts', '0010_user_geo_location_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('Man', posts.models.GenderChoices['MAN']), ('Woman', posts.models.GenderChoices['WOMAN']), ('Not matter', posts.models.GenderChoices['NOT_MATTER'])], max_length=255)),
                ('post_duration_hours', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Category')),
                ('photos', models.ManyToManyField(to='photos.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.Profile')),
            ],
        ),
    ]
