# Generated by Django 3.0.2 on 2020-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200518_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_age',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='post',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
    ]
