# Generated by Django 3.0.2 on 2020-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200605_1158'),
        ('posts', '0004_auto_20200608_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to='accounts.Profile'),
        ),
    ]
