# Generated by Django 3.0.2 on 2020-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_postimage'),
        ('posts', '0005_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(to='photos.PostImage'),
        ),
    ]
