# Generated by Django 3.0.2 on 2020-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_outdated',
            field=models.BooleanField(default=False),
        ),
    ]
