# Generated by Django 3.0.2 on 2020-08-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_is_outdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_outdated',
            new_name='is_active',
        ),
    ]
