# Generated by Django 3.0.2 on 2020-06-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='photos.Image'),
        ),
    ]
