# Generated by Django 3.0.2 on 2020-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
