# Generated by Django 3.0.2 on 2020-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200518_1346'),
        ('accounts', '0010_user_geo_location_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_posts',
            field=models.ManyToManyField(related_name='disliked_posts', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(related_name='favorite_posts', to='posts.Post'),
        ),
    ]
