# Generated by Django 3.0.2 on 2020-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200518_1346'),
        ('accounts', '0013_auto_20200525_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disliked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_posts', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_posts', to='posts.Post'),
        ),
    ]
