# Generated by Django 3.0.2 on 2020-07-27 13:42

from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_auto_20200605_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Post is hidden', notifications.models.ActionTypeChoices['POST_IS_HIDDEN']), ('New like', notifications.models.ActionTypeChoices['NEW_LIKE']), ('New match', notifications.models.ActionTypeChoices['NEW_MATCH'])], max_length=255)),
                ('notification_text', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.Profile')),
            ],
        ),
    ]
