# Generated by Django 3.0.2 on 2020-07-28 10:18

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('Post is hidden', notifications.models.ActionTypeChoices['POST_IS_HIDDEN']), ('New like', notifications.models.ActionTypeChoices['NEW_LIKE']), ('New match', notifications.models.ActionTypeChoices['NEW_MATCH']), ('New superlike', notifications.models.ActionTypeChoices['NEW_SUPERLIKE']), ('New listing response', notifications.models.ActionTypeChoices['NEW_LISTING_RESPONSE']), ('New message', notifications.models.ActionTypeChoices['NEW_MESSAGE']), ('New posts waiting', notifications.models.ActionTypeChoices['NEW_POSTS_WAITING'])], max_length=255),
        ),
    ]
