# Generated by Django 3.0.2 on 2020-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200527_1324'),
        ('chat', '0002_room_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='rooms', to='accounts.Profile'),
        ),
    ]
