# Generated by Django 3.0.2 on 2020-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200527_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='waiting_for_approve',
            field=models.BooleanField(default=True),
        ),
    ]
